#!/usr/bin/env bash
#This is a script that displays from 1 to 100
for (( i=1;i<101;i++ ))
do 
	if (( i%15==0 ))
	then
	       	echo "FizzBuzz"
	elif (( i%3==0 ))
	then
		echo "Fizz"

	elif (( i%5==0 ))
	then 
		echo "Buzz"

	else 
		echo "$i"
	fi

	
	#i=$((i+1))

done
