#!/usr/bin/env bash
#This script is displaying "Best School" 10 times
x=0
while [ $x -le 10 ];
do
	x=$(( x+1 ))
	echo "Best School"
	if [ $x -eq 4 ]
	then
		echo "bad luck"
	elif [ $x -eq 8 ]
	then 
		echo "good luck"
	else 	
		echo "value of x is othern than 4 and 8"
	
	fi
	
  
done
