#!/usr/bin/env bash
x=1
while [ $x -le 21 ]
do 
	case $x in
		4)
		       echo "$x"	
		       echo "bad luck for China"
		       x=$(($x+1))
		       ;;

		9)
			echo "$x"
			echo "bad luck from Japan"
			x=$(($x+1))
			;;

		17) 
			echo "$x"
			echo "bad luck from Italy"
			x=$(($x+1))
			;;


		*)
			echo "$x"
			x=$(($x+1))
			;;
	esac
done
