#!/usr/bin/env bash
#This script displays the time for 12 hours and 59 minutes
x=1
while [ $x -le 70 ]
do
	case $x in 
		minutes)
			echo "$x"
			echo "{1..59}"
			x=$((x+1))
			;;
		
		hours)
			echo "$x"
			echo "{1..12}"
			x=$((x+1))
			;;

		esac
	done

