#!/usr/bin/env bash
#This script displays if the file school exist or not 
if [-a school]
then 
	echo "school file exists"
	
	if [[ -f school ]]
		
		echo "school file is empty"	
 	fi
	if [ -s school ]
	     	
		echo "school file is not empty"
	fi
	if [ -f school ]

		echo "school is a regular file"
	
	fi
else 
	echo "school file does not exist"
fi

