#!/usr/bin/env bash
#
echo $$ > /var/run/myscript.pid 
while true
do
	trap 'echo "I hate the kill command"; rm -rf /var/run/myscript.pid; exit' SIGTERM
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'rm -rf /var/run/myscript.pid; exit' SIGQUIT

	echo "To infinity and beyond"
	sleep 2
done

